FROM maven:3.8-openjdk-17

WORKDIR /app

# Copy mvnw và .mvn trước (rất quan trọng!)
COPY mvnw .
COPY .mvn .mvn

# Copy pom.xml và tải dependencies trước
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source
# COPY src ./src
COPY . .

# Chạy với polling để phát hiện thay đổi file từ volume
ENV MAVEN_OPTS="-Dspring.devtools.restart.enabled=true -Dspring.devtools.restart.poll-interval=1000ms -Dspring.devtools.restart.quiet-period=400ms"

CMD ["./mvnw", "spring-boot:run"]